version: "3.7"
services:
#  bitcoin-normal:
#    build: .
#    image: lzhou1110/bitcoin-simulator:2016
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100' > ~/logs/bitcoin-normal.txt"
#    volumes:
#      - ./logs:/root/logs
#
#  bitcoin-relay-sendheader:
#    image: lzhou1110/bitcoin-simulator:2016
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100 --relayNetwork --sendheaders' > ~/logs/bitcoin-relay-sendheader.txt"
#    volumes:
#      - ./logs:/root/logs
#
#  bitcoin-relay-sendheader-upload:
#    image: lzhou1110/bitcoin-simulator:2016
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100 --relayNetwork --sendheaders --prioritiseUpload' > ~/logs/bitcoin-relay-sendheader-upload.txt"
#    volumes:
#      - ./logs:/root/logs



#  bitcoin-normal:
#    build: .
#    image: lzhou1110/bitcoin-simulator:2019
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100' > ~/logs/bitcoin-normal.txt"
#    volumes:
#      - ./logs:/root/logs
#
#  bitcoin-relay-sendheader:
#    image: lzhou1110/bitcoin-simulator:2019
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100 --relayNetwork --sendheaders' > ~/logs/bitcoin-relay-sendheader.txt"
#    volumes:
#      - ./logs:/root/logs
#
#  bitcoin-relay-sendheader-upload:
#    image: lzhou1110/bitcoin-simulator:2019
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100 --relayNetwork --sendheaders --prioritiseUpload' > ~/logs/bitcoin-relay-sendheader-upload.txt"
#    volumes:
#      - ./logs:/root/logs



#  bitcoin-normal:
#    build: .
#    image: lzhou1110/bitcoin-simulator:optimal
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100' > ~/logs/bitcoin-normal.txt"
#    volumes:
#      - ./logs:/root/logs
#
#  bitcoin-relay-sendheader:
#    image: lzhou1110/bitcoin-simulator:optimal
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100 --relayNetwork --sendheaders' > ~/logs/bitcoin-relay-sendheader.txt"
#    volumes:
#      - ./logs:/root/logs
#
#  bitcoin-relay-sendheader-upload:
#    image: lzhou1110/bitcoin-simulator:optimal
#    command: bash -c "mpirun --allow-run-as-root -n 32 ./waf --run 'bitcoin-test --noBlocks=10 --nodes=100 --relayNetwork --sendheaders --prioritiseUpload' > ~/logs/bitcoin-relay-sendheader-upload.txt"
#    volumes:
#      - ./logs:/root/logs